# Generated by Django 3.0.7 on 2020-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venture', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('General', 'General'), ('Social', 'Social')], max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('votes', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(default='user.png', upload_to='profile_pics')),
            ],
        ),
    ]
